test_6_repo

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,16 +31,16 @@ jobs:
           # 2. Run post.sh (This MUST create the 'releases' folder)
           ./post.sh
 
-      - name: Execute Python Indexing
-        run: |
-          # We do NOT pass arguments because your script uses a hardcoded BASE_DIR
-          # We check if the folder exists first to avoid script errors
-          if [ -d "releases" ]; then
-            python3 index.py
-          else
-            echo "::error::The 'releases' directory was not created by post.sh!"
-            exit 1
-          fi
+      # - name: Execute Python Indexing
+      #   run: |
+      #     # We do NOT pass arguments because your script uses a hardcoded BASE_DIR
+      #     # We check if the folder exists first to avoid script errors
+      #     if [ -d "releases" ]; then
+      #       python3 index.py
+      #     else
+      #       echo "::error::The 'releases' directory was not created by post.sh!"
+      #       exit 1
+      #     fi
 
       # - name: Save Release Folder as Artifact
       #   uses: actions/upload-artifact@v4
